version: '3.8'

services:
  spark-pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pipe_diario_de_bordo
    volumes:
      - ./data:/app/data          
      - ./.env:/app/.env:ro       
    environment:
      - PYTHONUNBUFFERED=1
    command: python3 main.py
  test-runner:
    build:
      context: .
    container_name: spark_pipeline_tests
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    command: pytest tests/
